### ISSUE TITLE
extension sometimes vanishes on Chrome Canary

### ISSUE THREAD

**Issue by DavidGretzschel** [dcchambers/vb4c#6]
Don't know how to replicate yet. I'll try to pay more attention.
When I observed it, it was fresh after a system restart. I had to reload the unpacked extension again and set up the chrome//extensions/shortcut again and bring it into the right position in my extension bar.
![image](https://user-images.githubusercontent.com/23729465/77455190-d53c3b00-6df9-11ea-991f-e8e8873303a9.png)

I've had more problems before with normal Chrome insisting that this Extension is dangerous and should be disabled (yes disable/no keep). 
The trouble was that another extension called "New Tab Redirect" would immediately load my preferred new-tab page, thus interrupt the dialog making it default to "yes disable".

Sorry that this is not particularly actionable yet, but this this more of a start for me (and others?) to add details once they are found. 
With Corona being such a big deal right now, who knows when Google will be able to finally review vb4c. So I think it might be valuable to not ignore such issues.

**Comment by DavidGretzschel** [comment]
oh uhm.... nevermind. I was not aware that one had to keep the extension folder from where on originally loaded it. This is extremely non-obvious, since it's reasonable to assume that Chrome would load the date into its own structure.
Please mention that in the installation description in the "README.md".

**Comment by knightofiam** [comment]
@dcchambers This issue is still relevant. Being new to your fork, and being used to installing via the Chrome Web Store, it took me a while to figure out why an unpacked extension install would vanish the next time I restarted Chrome. I still don't see any mention of this in the README. Let me know if you'd like me to submit a pull request explaining this in the Install section. I think it would save people time and headaches. And thank you for ongoing work, it's extremely appreciated!
